[package]
name = "day-4"
version = "0.1.0"
authors = ["Beno√Æt Faucon <faucon.benoit@cegetel.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
